services:
  # Backend API with Socket.io
  - type: web
    name: tigray-marketplace-api
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: tigray-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: CLOUDFRONT_URL
        sync: false
      - key: USE_S3
        value: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: noreply@tigraymarket.com
    healthCheckPath: /health
    autoDeploy: true

  # Background Worker for PDF generation
  - type: worker
    name: tigray-marketplace-worker
    runtime: docker
    dockerfilePath: ./worker/Dockerfile
    dockerContext: ./worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: tigray-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_URL
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: USE_S3
        value: false
      - key: BACKEND_URL
        sync: false
    autoDeploy: true

databases:
  # Managed Redis for Bull queues and Socket.io adapter
  - name: tigray-redis
    plan: starter
    maxmemoryPolicy: noeviction
    ipAllowList: []

