export const CATEGORIES = {
  'Vehicles': [
    'Cars',
    'Buses & Microbuses',
    'Trucks & Trailers',
    'Motorcycles & Bajaj',
    'Tractors & Heavy Equipment',
    'Spare Parts & Accessories',
    'Vehicle Services (Repair, Maintenance, Wash)',
    'Tires & Wheels',
    'Car Audio & Electronics',
    'Wanted Vehicles',
  ],
  'Property': [
    'Apartments for Rent',
    'Apartments for Sale',
    'Houses for Rent',
    'Houses for Sale',
    'Commercial Property for Rent (Offices, Shops, Warehouses)',
    'Commercial Property for Sale',
    'Land for Sale',
    'Land for Rent',
    'Short-term Rentals (Daily/Weekly)',
    'Roommates & Shared Apartments',
    'Property Wanted',
  ],
  'Mobile Phones & Tablets': [
    'Mobile Phones (New)',
    'Mobile Phones (Used)',
    'Tablets',
    'Mobile Accessories (Cases, Chargers, Screen Protectors)',
    'Smartwatches & Wearables',
    'Mobile Phone Services (Repair, Unlocking)',
    'Wholesale & Bulk Orders',
  ],
  'Electronics': [
    'Laptops & Computers',
    'Computer Accessories (Mouse, Keyboard, Webcam)',
    'TVs & Home Theater',
    'Audio Equipment (Speakers, Headphones)',
    'Cameras & Photography',
    'Gaming Consoles & Accessories',
    'Printers & Scanners',
    'Networking Equipment (Routers, Modems)',
    'Storage Devices (Hard Drives, USB)',
    'Electronics Repair Services',
  ],
  'Home, Furniture & Appliances': [
    'Living Room Furniture (Sofas, Tables, Chairs)',
    'Bedroom Furniture (Beds, Wardrobes, Dressers)',
    'Kitchen Furniture & Equipment',
    'Office Furniture',
    'Home Appliances (Refrigerators, Washing Machines)',
    'Kitchen Appliances (Stoves, Microwaves, Blenders)',
    'Home Decor & Accessories',
    'Garden & Outdoor',
    'Lighting & Fans',
    'Mattresses & Bedding',
  ],
  'Fashion': [
    "Men's Clothing",
    "Women's Clothing",
    "Kids' Clothing",
    "Shoes (Men's, Women's, Kids')",
    'Bags & Luggage',
    'Watches',
    'Jewelry & Accessories',
    'Traditional Clothing (Habesha Kemis, etc.)',
    'Sportswear & Athletic Shoes',
    'Wedding & Formal Wear',
  ],
  'Beauty & Personal Care': [
    'Skincare Products',
    'Makeup & Cosmetics',
    'Hair Care Products',
    'Perfumes & Fragrances',
    'Hair Extensions & Wigs',
    'Beauty Tools & Equipment',
    'Salon & Spa Services',
    'Barbershop Services',
    'Personal Hygiene Products',
    "Men's Grooming",
  ],
  'Services': [
    'Cleaning Services (Home, Office, Sofa)',
    'Event Planning & Catering',
    'Photography & Videography',
    'Tutoring & Education',
    'IT & Tech Support',
    'Web Development & Design',
    'Graphic Design',
    'Translation Services',
    'Legal Services',
    'Accounting & Tax Services',
    'Moving & Logistics',
  ],
  'Repair & Construction': [
    'Construction Services (Building, Renovation)',
    'Electrical Services',
    'Plumbing Services',
    'Carpentry & Woodwork',
    'Painting & Decoration',
    'Welding & Metalwork',
    'Tile & Marble Installation',
    'Roofing Services',
    'HVAC Services',
    'Building Materials',
  ],
  'Commercial Equipment & Tools': [
    'Restaurant Equipment',
    'Bakery Equipment',
    'Construction Equipment',
    'Factory & Industrial Equipment',
    'Printing & Publishing Equipment',
    'Medical Equipment',
    'Salon & Barber Equipment',
    'Shop Fixtures & Displays',
    'Power Tools',
    'Agricultural Equipment',
  ],
  'Leisure & Activities': [
    'Sports Equipment (Football, Basketball, Gym)',
    'Gym & Fitness',
    'Musical Instruments',
    'Books & Magazines',
    'CDs, DVDs & Media',
    'Toys & Games',
    'Bicycles',
    'Camping & Outdoor Gear',
    'Tickets & Events',
    'Hobbies & Crafts',
  ],
  'Babies & Kids': [
    'Baby Clothing',
    'Baby Furniture (Cribs, High Chairs)',
    'Strollers & Car Seats',
    'Baby Feeding & Nursing',
    'Diapers & Baby Care',
    'Toys & Games',
    "Kids' Shoes",
    'School Supplies & Books',
    "Kids' Bikes & Ride-ons",
    'Maternity Products',
  ],
  'Food, Agriculture & Farming': [
    'Fresh Produce (Vegetables, Fruits)',
    'Grains & Cereals',
    'Livestock (Cattle, Sheep, Goats)',
    'Poultry & Eggs',
    'Animal Feed',
    'Seeds & Fertilizers',
    'Farm Equipment & Machinery',
    'Irrigation Equipment',
    'Beekeeping & Honey',
    'Processed Foods & Spices',
  ],
  'Animals & Pets': [
    'Dogs',
    'Cats',
    'Birds',
    'Fish & Aquariums',
    'Small Animals (Rabbits, Guinea Pigs)',
    'Pet Food & Supplies',
    'Pet Accessories',
    'Pet Grooming & Services',
    'Veterinary Services',
    'Animal Breeding Services',
  ],
  'Jobs': [
    'Accounting & Finance Jobs',
    'Sales & Marketing Jobs',
    'IT & Software Jobs',
    'Engineering Jobs',
    'Healthcare & Medical Jobs',
    'Customer Service Jobs',
    'Teaching & Education Jobs',
    'Hospitality & Tourism Jobs',
    'Construction & Trade Jobs',
    'Driver Jobs',
    'Security Jobs',
    'Administrative & Office Jobs',
    'Manufacturing & Production Jobs',
    'Part-time & Freelance',
    'Internships',
    'Domestic & Household Jobs',
  ],
};

export const PAYMENT_METHODS = [
  'Bank transfer',
  'Telebirr',
  'M-Pesa',
];


